// const machineData = [
//   {
//     id: 1,
//     name: "Machine 1",
//     fuelConsumed: "500 L",
//     powerGenerated: "2000 ",
//   },
//   {
//     id: 2,
//     name: "Machine 2",
//     fuelConsumed: "700 L",
//     powerGenerated: "2500 ",
//   },
//   {
//     id: 3,
//     name: "Machine 3",
//     fuelConsumed: "600 L",
//     powerGenerated: "2200 ",
//   },
//   {
//     id: 4,
//     name: "Machine 4",
//     fuelConsumed: "600 L",
//     powerGenerated: "2200 ",
//   },
// ];

// export default machineData;

const machineData = [
  {
    id: 1,
    name: "Machine 1",
    fuelConsumed: "500 L",
    powerGenerated: "2000 ",
    yearlyData: [
      { month: "January", fuelUsed: "400 L", powerGenerated: "1600 " },
      { month: "February", fuelUsed: "350 L", powerGenerated: "1400 " },
      { month: "March", fuelUsed: "380 L", powerGenerated: "1520 " },
      { month: "April", fuelUsed: "420 L", powerGenerated: "1680 " },
      { month: "May", fuelUsed: "450 L", powerGenerated: "1800 " },
      { month: "June", fuelUsed: "480 L", powerGenerated: "1920 " },
      { month: "July", fuelUsed: "490 L", powerGenerated: "1960 " },
      { month: "August", fuelUsed: "500 L", powerGenerated: "2000 " },
      { month: "September", fuelUsed: "480 L", powerGenerated: "1920 " },
      { month: "October", fuelUsed: "450 L", powerGenerated: "1800 " },
      { month: "November", fuelUsed: "400 L", powerGenerated: "1600 " },
      { month: "December", fuelUsed: "380 L", powerGenerated: "1520 " },
    ],
  },
  {
    id: 2,
    name: "Machine 2",
    fuelConsumed: "700 L",
    powerGenerated: "2500 ",
    yearlyData: [
      { month: "January", fuelUsed: "450 L", powerGenerated: "1800 " },
      { month: "February", fuelUsed: "400 L", powerGenerated: "1600 " },
      { month: "March", fuelUsed: "430 L", powerGenerated: "1720 " },
      { month: "April", fuelUsed: "470 L", powerGenerated: "1880 " },
      { month: "May", fuelUsed: "500 L", powerGenerated: "2000 " },
      { month: "June", fuelUsed: "520 L", powerGenerated: "2080 " },
      { month: "July", fuelUsed: "530 L", powerGenerated: "2120 " },
      { month: "August", fuelUsed: "550 L", powerGenerated: "2200 " },
      { month: "September", fuelUsed: "520 L", powerGenerated: "2080 " },
      { month: "October", fuelUsed: "500 L", powerGenerated: "2000 " },
      { month: "November", fuelUsed: "450 L", powerGenerated: "1800 " },
      { month: "December", fuelUsed: "430 L", powerGenerated: "1720 " },
    ],
  },
  {
    id: 3,
    name: "Machine 3",
    fuelConsumed: "600 L",
    powerGenerated: "2200 ",
    yearlyData: [
      { month: "January", fuelUsed: "380 L", powerGenerated: "1520 " },
      { month: "February", fuelUsed: "350 L", powerGenerated: "1400 " },
      { month: "March", fuelUsed: "370 L", powerGenerated: "1480 " },
      { month: "April", fuelUsed: "400 L", powerGenerated: "1600 " },
      { month: "May", fuelUsed: "430 L", powerGenerated: "1720 " },
      { month: "June", fuelUsed: "450 L", powerGenerated: "1800 " },
      { month: "July", fuelUsed: "460 L", powerGenerated: "1840 " },
      { month: "August", fuelUsed: "470 L", powerGenerated: "0000 " },
      { month: "September", fuelUsed: "450 L", powerGenerated: "1800 " },
      { month: "October", fuelUsed: "430 L", powerGenerated: "1720 " },
      { month: "November", fuelUsed: "400 L", powerGenerated: "1600 " },
      { month: "December", fuelUsed: "380 L", powerGenerated: "1520 " },
    ],
  },
  {
    id: 4,
    name: "Machine 4",
    fuelConsumed: "600 L",
    powerGenerated: "2200 ",
    yearlyData: [
      { month: "January", fuelUsed: "380 L", powerGenerated: "1520 " },
      { month: "February", fuelUsed: "350 L", powerGenerated: "1400 " },
      { month: "March", fuelUsed: "370 L", powerGenerated: "1480 " },
      { month: "April", fuelUsed: "400 L", powerGenerated: "1600 " },
      { month: "May", fuelUsed: "430 L", powerGenerated: "1720 " },
      { month: "June", fuelUsed: "450 L", powerGenerated: "1800 " },
      { month: "July", fuelUsed: "460 L", powerGenerated: "1840 " },
      { month: "August", fuelUsed: "470 L", powerGenerated: "1880 " },
      { month: "September", fuelUsed: "450 L", powerGenerated: "1800 " },
      { month: "October", fuelUsed: "430 L", powerGenerated: "1720 " },
      { month: "November", fuelUsed: "400 L", powerGenerated: "1600 " },
      { month: "December", fuelUsed: "380 L", powerGenerated: "1520 " },
    ],
  },
];

export default machineData;
